version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    networks:
      - calerino
    depends_on:
      - mariadb
    volumes:
      - ./:/var/www/html

  web-queue:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - calerino
    depends_on:
      - web
    volumes:
      - ./:/var/www/html
    command: ["php", "artisan", "queue:work", "--delay=60"]

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - calerino
    volumes:
      - ./mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8586:80
    environment:
      - PMA_HOST=mariadb
    networks:
      - calerino
    depends_on:
      - mariadb

networks:
  calerino:
    driver: bridge
